### ISSUE TITLE
Update workflow file on GitHub Action installation

### ISSUE THREAD

**Issue by shay2025** [reviewpad/docs#172]
**Describe the bug**
Currently, on the GitHub Action workflow file presented in https://docs.reviewpad.com/getting-started/installation-action-tokenized#step-4-add-reviewpad-action-workflow-file, the action will only be triggered by events on `issues` and `pull_request` however the `pull_request` event does not include the subevent `issues_comment` (replaces `pull_request_comment`) - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request - and this event is needed in order to the Reviewpad commands to function.

**To Reproduce**
1. Install the GitHub Action on a repo with the workflow file in https://docs.reviewpad.com/getting-started/installation-action-tokenized#step-4-add-reviewpad-action-workflow-file
2. Open a pull request
3. Run a Reviewpad command, e.g., `/reviewpad assign-reviewers`

**Expected behavior**
The file should mention the trigger event `issues_comment`.
```
name: Reviewpad Action

on:
    - issues
    - pull_request
    - issues_comment

jobs:
    reviewpad-action:
        runs-on: ubuntu-latest
        steps:
            - name: Running reviewpad action
              uses: reviewpad/action@v3.x
              with:
                  token: ${{ secrets.GH_TOKEN }}
```
