### ISSUE TITLE
`hasCodeWithoutSemanticChanges` not working on the playground

### ISSUE THREAD

**Issue by adrianoapmartins** [reviewpad/docs#258]
## Describe the bug

I'm not being able to try hasCodeWithoutSemanticChanges on the playground, is that also supposed to happen?

## How to reproduce

https://play.reviewpad.com/Ip2gjd
```yml
workflows:
  - name: automating-safe-approvals-for-low-risk-changes
    if:
      - rule: '!$isDraft()
             && $hasCodeWithoutSemanticChanges(["**/*.js", "src/server/**/*.py"])
             && !$hasFilePattern("src/package.json")'
    then:
      - $approve("LGTM! This PR contains only low-risk code changes")
```

## Expected behavior

```
# List of actions triggered

> Error: GET https://api.github.com/repos/reviewpad/reviewpad/contents/?ref=reviewpad-service-ping: 404 No commit found for the ref reviewpad-service-ping []
```
