### ISSUE TITLE
Add documentation for the workflow "on" property

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/docs#37]
**Is your feature request related to a problem? Please describe.**
With the introduction of reviewpad to issue we now have the property `on` on the workflow.

e.g.
```yml
workflows:
  - name: empty-description
    on: # <----- the new property
      - "issue"
    if:
      - $description() == ""
    then: 
      - $error("Please add a description")'
```

**Describe the solution you'd like**
Document the new property `on` under the section `docs/guides/syntax.md`.
