### ISSUE TITLE
New version of docs can't be released due to a wrong redirect to `/reviewpad-checker`

### ISSUE THREAD

**Issue by fmallet** [reviewpad/docs#385]
## Describe the bug

The following redirect in `docusaurus.config.js` configuration file should redirect to  `/reviewpad-check` and not to `/reviewpad-checker`.

```yaml
{
  to: '/reviewpad-checker',
  from: '/guides/checks',
},
```

As a consequence, the deployment of any new version of the docs fails.
