### ISSUE TITLE
Add use case for git conflicts

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/docs#52]
**Is your feature request related to a problem? Please describe.**
We need to add a use case to the section https://docs.reviewpad.com/use-cases with the labelling of git conflicts in pull requests.

The following Reviewpad and GitHub action configurations should be enough to get automatically labelling of pull requests that have git conflicts.

**Reviewpad Configuration**

```yml
api-version: reviewpad.com/v3.x

workflows:
  - name: label-pull-requests-with-git-conflicts
    if:
      -$hasGitConflicts()
    then:
      - $addLabel("conflicts")
```

**GitHub Action**

```yml
name: Reviewpad

on:
  push:
    branches:
       - main

jobs:
  reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Reviewpad
        uses: reviewpad/action@v3.x
```
