### ISSUE TITLE
Set required approvals use case

### ISSUE THREAD

**Issue by shay2025** [reviewpad/docs#77]
In `/use-cases`, we could add the use case of being able to set a required number of approvals, depending on who approves, and if the pull request doesn't follow that then the merge is blocked (the action fails).

It is also needed to check if the action can block the merge button.

Use case:
```yaml
workflows:
    - name: set-required-approvals
      if:
        - $any($team("core"), ($dev => $reviewerStatus($dev) == "APPROVED"))
      then:
        - $fail("Blocking the merge")
```
